Repository maca-11/CUI_vending_machie, pull requests merged in 2025-02, with the labels that each got.

#25 タイトルと商品一覧のWBS #22 #23
  WBS/タイトルWBS.pu
  WBS/商品一覧WBS.pu
Labels: SBI

#32 全体工程図のフローチャートを提出
  フローチャート/全体工程.pu
Labels: SBI

#40 流れ図#29 #30 #31
  README.md
  souce/README.md
  フローチャート/タイトル画面の流れ図.pu
  フローチャート/商品一覧の流れ図.pu
  フローチャート/支払処理の流れ図.pu
Labels: SBI

#42 タイトル画面#7 #8
  souce/タイトル画面.py
Labels: PBI

#43 商品一覧　#9 #10 #12 #13
  souce/商品一覧の表示.py
Labels: S1

#44 管理者画面#16
  souce/管理者画面.py
Labels: SBI, S2

#51 タイトル画面テスト#47
  tests/title_test.py
Labels: PBI, S2

#53 コードの修正１
  souce/商品一覧の表示.py
  souce/管理者画面.py
  tests/管理者.py
Labels: S1

#55 統合とテストコード
  CUI.py
  tests/管理者.py
Labels: PBI, S2

#56 動作確認#54
  動作確認/スクリーンショット 2025-02-17 134628.png
  動作確認/スクリーンショット 2025-02-17 134649.png
  動作確認/スクリーンショット 2025-02-17 134850.png
  動作確認/スクリーンショット 2025-02-17 134919.png
  動作確認/スクリーンショット 2025-02-17 135151.png
Labels: PBI, S1
